# syntax=docker/dockerfile:1.7

FROM node:24-alpine AS build
WORKDIR /app
ENV ASTRO_TELEMETRY_DISABLED=1
ARG PUBLIC_UMAMI_SCRIPT_URL
ARG PUBLIC_UMAMI_WEBSITE_ID
ARG PUBLIC_UMAMI_DOMAINS
ARG PUBLIC_LEGAL_REVIEWED=false
ARG PUBLIC_LEGAL_CONTROLLER_NAME="Sören Schröder"
ARG PUBLIC_LEGAL_CONTROLLER_ADDRESS="Max-Brauer-Allee 167f, 22765 Hamburg, Germany"
ARG PUBLIC_LEGAL_CONTROLLER_EMAIL=support@filius.app
ARG PUBLIC_LEGAL_CONTROLLER_PHONE
ARG PUBLIC_LEGAL_VAT_ID
ARG PUBLIC_LEGAL_REGISTER_ENTRY
ARG PUBLIC_HOSTING_PROVIDER_NAME="Oracle Cloud Infrastructure (Oracle Deutschland B.V. & Co. KG)"
ARG PUBLIC_HOSTING_PROVIDER_ADDRESS="Riesstraße 25, 80992 München"
ARG PUBLIC_HOSTING_COUNTRY=Germany
ARG PUBLIC_HOSTING_REGION=eu-frankfurt-1
ARG PUBLIC_CLOUDFLARE_PROXY_ENABLED=true
ARG PUBLIC_ACCESS_LOG_RETENTION_DAYS=35
ARG PUBLIC_ERROR_LOG_RETENTION_DAYS=77
ARG PUBLIC_EMAIL_PROVIDER_NAME="mailbox-provider GmbH"
ARG PUBLIC_EMAIL_PROVIDER_ADDRESS="Emmy-Noether-Straße 10, 76131 Karlsruhe, Germany"
ARG PUBLIC_EMAIL_PROVIDER_COUNTRY=Germany
ARG PUBLIC_EMAIL_PROVIDER_MODE=mailbox-provider-mailbox
ARG PUBLIC_SUPPORT_RETENTION_DAYS=180
ARG PUBLIC_CONTACT_RATE_LIMIT_WINDOW_MINUTES=15
ARG PUBLIC_ANALYTICS_RETENTION_DAYS=180
ARG PUBLIC_PRIVACY_NOTICE_DATE="6 August 2026"
ENV PUBLIC_UMAMI_SCRIPT_URL=$PUBLIC_UMAMI_SCRIPT_URL \
    PUBLIC_UMAMI_WEBSITE_ID=$PUBLIC_UMAMI_WEBSITE_ID \
    PUBLIC_UMAMI_DOMAINS=$PUBLIC_UMAMI_DOMAINS \
    PUBLIC_LEGAL_REVIEWED=$PUBLIC_LEGAL_REVIEWED \
    PUBLIC_LEGAL_CONTROLLER_NAME=$PUBLIC_LEGAL_CONTROLLER_NAME \
    PUBLIC_LEGAL_CONTROLLER_ADDRESS=$PUBLIC_LEGAL_CONTROLLER_ADDRESS \
    PUBLIC_LEGAL_CONTROLLER_EMAIL=$PUBLIC_LEGAL_CONTROLLER_EMAIL \
    PUBLIC_LEGAL_CONTROLLER_PHONE=$PUBLIC_LEGAL_CONTROLLER_PHONE \
    PUBLIC_LEGAL_VAT_ID=$PUBLIC_LEGAL_VAT_ID \
    PUBLIC_LEGAL_REGISTER_ENTRY=$PUBLIC_LEGAL_REGISTER_ENTRY \
    PUBLIC_HOSTING_PROVIDER_NAME=$PUBLIC_HOSTING_PROVIDER_NAME \
    PUBLIC_HOSTING_PROVIDER_ADDRESS=$PUBLIC_HOSTING_PROVIDER_ADDRESS \
    PUBLIC_HOSTING_COUNTRY=$PUBLIC_HOSTING_COUNTRY \
    PUBLIC_HOSTING_REGION=$PUBLIC_HOSTING_REGION \
    PUBLIC_CLOUDFLARE_PROXY_ENABLED=$PUBLIC_CLOUDFLARE_PROXY_ENABLED \
    PUBLIC_ACCESS_LOG_RETENTION_DAYS=$PUBLIC_ACCESS_LOG_RETENTION_DAYS \
    PUBLIC_ERROR_LOG_RETENTION_DAYS=$PUBLIC_ERROR_LOG_RETENTION_DAYS \
    PUBLIC_EMAIL_PROVIDER_NAME=$PUBLIC_EMAIL_PROVIDER_NAME \
    PUBLIC_EMAIL_PROVIDER_ADDRESS=$PUBLIC_EMAIL_PROVIDER_ADDRESS \
    PUBLIC_EMAIL_PROVIDER_COUNTRY=$PUBLIC_EMAIL_PROVIDER_COUNTRY \
    PUBLIC_EMAIL_PROVIDER_MODE=$PUBLIC_EMAIL_PROVIDER_MODE \
    PUBLIC_SUPPORT_RETENTION_DAYS=$PUBLIC_SUPPORT_RETENTION_DAYS \
    PUBLIC_CONTACT_RATE_LIMIT_WINDOW_MINUTES=$PUBLIC_CONTACT_RATE_LIMIT_WINDOW_MINUTES \
    PUBLIC_ANALYTICS_RETENTION_DAYS=$PUBLIC_ANALYTICS_RETENTION_DAYS \
    PUBLIC_PRIVACY_NOTICE_DATE=$PUBLIC_PRIVACY_NOTICE_DATE
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm npm ci
COPY . .
RUN npm run validate

FROM nginxinc/nginx-unprivileged:1-alpine AS runtime
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY nginx/security-headers.conf /etc/nginx/snippets/security-headers.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -q -O /dev/null http://127.0.0.1:8080/healthz || exit 1
